apiVersion: v2
name: travel-planner
description: A Helm chart for Travel Planner App with microservices
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - travel
  - ml
  - devops
  - kubernetes
  - argocd
home: https://github.com/Card1sTree/travel-planner
maintainers:
  - name: Your Name
    email: your.email@example.com
